// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.so_analysis_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SoAnalysisNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class SoElfHeader (
  val magic: String,
  val classType: String,
  val dataEncoding: String,
  val osAbi: String,
  val fileType: String,
  val machine: String,
  val entryPoint: Long,
  val programHeaderOffset: Long,
  val sectionHeaderOffset: Long,
  val flags: Long,
  val programHeaderCount: Long,
  val sectionHeaderCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoElfHeader {
      val magic = pigeonVar_list[0] as String
      val classType = pigeonVar_list[1] as String
      val dataEncoding = pigeonVar_list[2] as String
      val osAbi = pigeonVar_list[3] as String
      val fileType = pigeonVar_list[4] as String
      val machine = pigeonVar_list[5] as String
      val entryPoint = pigeonVar_list[6] as Long
      val programHeaderOffset = pigeonVar_list[7] as Long
      val sectionHeaderOffset = pigeonVar_list[8] as Long
      val flags = pigeonVar_list[9] as Long
      val programHeaderCount = pigeonVar_list[10] as Long
      val sectionHeaderCount = pigeonVar_list[11] as Long
      return SoElfHeader(magic, classType, dataEncoding, osAbi, fileType, machine, entryPoint, programHeaderOffset, sectionHeaderOffset, flags, programHeaderCount, sectionHeaderCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      magic,
      classType,
      dataEncoding,
      osAbi,
      fileType,
      machine,
      entryPoint,
      programHeaderOffset,
      sectionHeaderOffset,
      flags,
      programHeaderCount,
      sectionHeaderCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoElfHeader) {
      return false
    }
    if (this === other) {
      return true
    }
    return SoAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SoSection (
  val name: String,
  val type: String,
  val offset: Long,
  val size: Long,
  val flags: Long,
  val alignment: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoSection {
      val name = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val offset = pigeonVar_list[2] as Long
      val size = pigeonVar_list[3] as Long
      val flags = pigeonVar_list[4] as Long
      val alignment = pigeonVar_list[5] as Long
      return SoSection(name, type, offset, size, flags, alignment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      type,
      offset,
      size,
      flags,
      alignment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoSection) {
      return false
    }
    if (this === other) {
      return true
    }
    return SoAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SoSymbol (
  val name: String,
  val type: String,
  val binding: String,
  val visibility: String,
  val address: Long,
  val size: Long,
  val shndx: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoSymbol {
      val name = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val binding = pigeonVar_list[2] as String
      val visibility = pigeonVar_list[3] as String
      val address = pigeonVar_list[4] as Long
      val size = pigeonVar_list[5] as Long
      val shndx = pigeonVar_list[6] as String?
      return SoSymbol(name, type, binding, visibility, address, size, shndx)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      type,
      binding,
      visibility,
      address,
      size,
      shndx,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoSymbol) {
      return false
    }
    if (this === other) {
      return true
    }
    return SoAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SoDependency (
  val name: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoDependency {
      val name = pigeonVar_list[0] as String
      return SoDependency(name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoDependency) {
      return false
    }
    if (this === other) {
      return true
    }
    return SoAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SoJniFunction (
  val symbolName: String,
  val javaClass: String,
  val javaMethod: String,
  val signature: String? = null,
  val address: Long,
  val isDynamic: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoJniFunction {
      val symbolName = pigeonVar_list[0] as String
      val javaClass = pigeonVar_list[1] as String
      val javaMethod = pigeonVar_list[2] as String
      val signature = pigeonVar_list[3] as String?
      val address = pigeonVar_list[4] as Long
      val isDynamic = pigeonVar_list[5] as Boolean
      return SoJniFunction(symbolName, javaClass, javaMethod, signature, address, isDynamic)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      symbolName,
      javaClass,
      javaMethod,
      signature,
      address,
      isDynamic,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoJniFunction) {
      return false
    }
    if (this === other) {
      return true
    }
    return SoAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SoString (
  val offset: Long,
  val value: String,
  val section: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SoString {
      val offset = pigeonVar_list[0] as Long
      val value = pigeonVar_list[1] as String
      val section = pigeonVar_list[2] as String
      return SoString(offset, value, section)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      offset,
      value,
      section,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SoString) {
      return false
    }
    if (this === other) {
      return true
    }
    return SoAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class SoAnalysisNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoElfHeader.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoSection.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoSymbol.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoDependency.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoJniFunction.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SoString.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SoElfHeader -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is SoSection -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is SoSymbol -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SoDependency -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SoJniFunction -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SoString -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SoAnalysisNative {
  fun parseSoHeader(sessionId: String, soPath: String, callback: (Result<SoElfHeader>) -> Unit)
  fun getSoSections(sessionId: String, soPath: String, callback: (Result<List<SoSection>>) -> Unit)
  fun getExportedSymbols(sessionId: String, soPath: String, callback: (Result<List<SoSymbol>>) -> Unit)
  fun getImportedSymbols(sessionId: String, soPath: String, callback: (Result<List<SoSymbol>>) -> Unit)
  fun getDependencies(sessionId: String, soPath: String, callback: (Result<List<SoDependency>>) -> Unit)
  fun getJniFunctions(sessionId: String, soPath: String, callback: (Result<List<SoJniFunction>>) -> Unit)
  fun getSoStrings(sessionId: String, soPath: String, callback: (Result<List<SoString>>) -> Unit)
  fun generateFridaHook(sessionId: String, soPath: String, symbolName: String, address: Long, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by SoAnalysisNative. */
    val codec: MessageCodec<Any?> by lazy {
      SoAnalysisNativePigeonCodec()
    }
    /** Sets up an instance of `SoAnalysisNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SoAnalysisNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.parseSoHeader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.parseSoHeader(sessionIdArg, soPathArg) { result: Result<SoElfHeader> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.getSoSections$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.getSoSections(sessionIdArg, soPathArg) { result: Result<List<SoSection>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.getExportedSymbols$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.getExportedSymbols(sessionIdArg, soPathArg) { result: Result<List<SoSymbol>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.getImportedSymbols$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.getImportedSymbols(sessionIdArg, soPathArg) { result: Result<List<SoSymbol>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.getDependencies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.getDependencies(sessionIdArg, soPathArg) { result: Result<List<SoDependency>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.getJniFunctions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.getJniFunctions(sessionIdArg, soPathArg) { result: Result<List<SoJniFunction>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.getSoStrings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            api.getSoStrings(sessionIdArg, soPathArg) { result: Result<List<SoString>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.SoAnalysisNative.generateFridaHook$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val soPathArg = args[1] as String
            val symbolNameArg = args[2] as String
            val addressArg = args[3] as Long
            api.generateFridaHook(sessionIdArg, soPathArg, symbolNameArg, addressArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SoAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SoAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
