// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.pinia_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PiniaNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class PiniaNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PiniaNative {
  fun setString(space: String, key: String, value: String, type: Long)
  fun setInt(space: String, key: String, value: Long, type: Long)
  fun setBool(space: String, key: String, value: Boolean, type: Long)
  fun setDouble(space: String, key: String, value: Double, type: Long)
  fun setLong(space: String, key: String, value: Long, type: Long)
  fun getString(space: String, key: String, defaultValue: String, type: Long): String
  fun getInt(space: String, key: String, defaultValue: Long, type: Long): Long
  fun getBool(space: String, key: String, defaultValue: Boolean, type: Long): Boolean
  fun getDouble(space: String, key: String, defaultValue: Double, type: Long): Double
  fun getLong(space: String, key: String, defaultValue: Long, type: Long): Long
  fun contains(space: String, key: String, type: Long): Boolean
  fun remove(space: String, key: String, type: Long)
  fun clear(space: String, type: Long)

  companion object {
    /** The codec used by PiniaNative. */
    val codec: MessageCodec<Any?> by lazy {
      PiniaNativePigeonCodec()
    }
    /** Sets up an instance of `PiniaNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PiniaNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.setString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val valueArg = args[2] as String
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              api.setString(spaceArg, keyArg, valueArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.setInt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val valueArg = args[2] as Long
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              api.setInt(spaceArg, keyArg, valueArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.setBool$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val valueArg = args[2] as Boolean
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              api.setBool(spaceArg, keyArg, valueArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.setDouble$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val valueArg = args[2] as Double
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              api.setDouble(spaceArg, keyArg, valueArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.setLong$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val valueArg = args[2] as Long
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              api.setLong(spaceArg, keyArg, valueArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.getString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val defaultValueArg = args[2] as String
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getString(spaceArg, keyArg, defaultValueArg, typeArg))
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.getInt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val defaultValueArg = args[2] as Long
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getInt(spaceArg, keyArg, defaultValueArg, typeArg))
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.getBool$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val defaultValueArg = args[2] as Boolean
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getBool(spaceArg, keyArg, defaultValueArg, typeArg))
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.getDouble$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val defaultValueArg = args[2] as Double
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getDouble(spaceArg, keyArg, defaultValueArg, typeArg))
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.getLong$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val defaultValueArg = args[2] as Long
            val typeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getLong(spaceArg, keyArg, defaultValueArg, typeArg))
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.contains$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val typeArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.contains(spaceArg, keyArg, typeArg))
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.remove$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val keyArg = args[1] as String
            val typeArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.remove(spaceArg, keyArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.PiniaNative.clear$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val spaceArg = args[0] as String
            val typeArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.clear(spaceArg, typeArg)
              listOf(null)
            } catch (exception: Throwable) {
              PiniaNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
