// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.app_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AppNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 应用信息数据模型 (按照 status_management.dart 的模式定义)
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AppInfo (
  val name: String,
  val packageName: String,
  val versionName: String,
  val versionCode: Long,
  val isSystemApp: Boolean,
  val icon: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppInfo {
      val name = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val versionName = pigeonVar_list[2] as String
      val versionCode = pigeonVar_list[3] as Long
      val isSystemApp = pigeonVar_list[4] as Boolean
      val icon = pigeonVar_list[5] as ByteArray?
      return AppInfo(name, packageName, versionName, versionCode, isSystemApp, icon)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      packageName,
      versionName,
      versionCode,
      isSystemApp,
      icon,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AppInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return AppNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class AppNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AppInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AppNative {
  /** 获取符合条件的已安装应用总数 */
  fun getAppCount(includeSystemApps: Boolean, query: String): Long
  /** 异步分页获取应用列表 (取代半手动的 EventChannel) */
  fun getInstalledApps(includeSystemApps: Boolean, offset: Long, limit: Long, query: String, callback: (Result<List<AppInfo>>) -> Unit)
  /** 根据包名获取单个应用详情 */
  fun getAppByPackageName(packageName: String, callback: (Result<AppInfo?>) -> Unit)
  fun openAppX(packageName: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by AppNative. */
    val codec: MessageCodec<Any?> by lazy {
      AppNativePigeonCodec()
    }
    /** Sets up an instance of `AppNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AppNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.AppNative.getAppCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val includeSystemAppsArg = args[0] as Boolean
            val queryArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.getAppCount(includeSystemAppsArg, queryArg))
            } catch (exception: Throwable) {
              AppNativePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.AppNative.getInstalledApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val includeSystemAppsArg = args[0] as Boolean
            val offsetArg = args[1] as Long
            val limitArg = args[2] as Long
            val queryArg = args[3] as String
            api.getInstalledApps(includeSystemAppsArg, offsetArg, limitArg, queryArg) { result: Result<List<AppInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.AppNative.getAppByPackageName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getAppByPackageName(packageNameArg) { result: Result<AppInfo?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.AppNative.openAppX$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.openAppX(packageNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(AppNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
