// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.apk_analysis_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ApkAnalysisNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ApkAsset (
  val path: String,
  val name: String,
  val size: Long,
  val compressedSize: Long,
  val isDirectory: Boolean,
  val lastModified: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkAsset {
      val path = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val size = pigeonVar_list[2] as Long
      val compressedSize = pigeonVar_list[3] as Long
      val isDirectory = pigeonVar_list[4] as Boolean
      val lastModified = pigeonVar_list[5] as Long
      return ApkAsset(path, name, size, compressedSize, isDirectory, lastModified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      name,
      size,
      compressedSize,
      isDirectory,
      lastModified,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ApkAsset) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApkAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApkComponent (
  val name: String,
  val exported: Boolean,
  val process: String? = null,
  val intentActions: List<String?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkComponent {
      val name = pigeonVar_list[0] as String
      val exported = pigeonVar_list[1] as Boolean
      val process = pigeonVar_list[2] as String?
      val intentActions = pigeonVar_list[3] as List<String?>
      return ApkComponent(name, exported, process, intentActions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      exported,
      process,
      intentActions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ApkComponent) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApkAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApkManifest (
  val packageName: String,
  val versionName: String,
  val versionCode: Long,
  val minSdk: Long,
  val targetSdk: Long,
  val permissions: List<String?>,
  val activities: List<ApkComponent?>,
  val services: List<ApkComponent?>,
  val receivers: List<ApkComponent?>,
  val providers: List<ApkComponent?>,
  val applicationLabel: String? = null,
  val debuggable: Boolean,
  val allowBackup: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkManifest {
      val packageName = pigeonVar_list[0] as String
      val versionName = pigeonVar_list[1] as String
      val versionCode = pigeonVar_list[2] as Long
      val minSdk = pigeonVar_list[3] as Long
      val targetSdk = pigeonVar_list[4] as Long
      val permissions = pigeonVar_list[5] as List<String?>
      val activities = pigeonVar_list[6] as List<ApkComponent?>
      val services = pigeonVar_list[7] as List<ApkComponent?>
      val receivers = pigeonVar_list[8] as List<ApkComponent?>
      val providers = pigeonVar_list[9] as List<ApkComponent?>
      val applicationLabel = pigeonVar_list[10] as String?
      val debuggable = pigeonVar_list[11] as Boolean
      val allowBackup = pigeonVar_list[12] as Boolean
      return ApkManifest(packageName, versionName, versionCode, minSdk, targetSdk, permissions, activities, services, receivers, providers, applicationLabel, debuggable, allowBackup)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      versionName,
      versionCode,
      minSdk,
      targetSdk,
      permissions,
      activities,
      services,
      receivers,
      providers,
      applicationLabel,
      debuggable,
      allowBackup,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ApkManifest) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApkAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DexClass (
  val className: String,
  val superClass: String? = null,
  val interfaces: List<String?>,
  val methodCount: Long,
  val fieldCount: Long,
  val isAbstract: Boolean,
  val isInterface: Boolean,
  val isEnum: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DexClass {
      val className = pigeonVar_list[0] as String
      val superClass = pigeonVar_list[1] as String?
      val interfaces = pigeonVar_list[2] as List<String?>
      val methodCount = pigeonVar_list[3] as Long
      val fieldCount = pigeonVar_list[4] as Long
      val isAbstract = pigeonVar_list[5] as Boolean
      val isInterface = pigeonVar_list[6] as Boolean
      val isEnum = pigeonVar_list[7] as Boolean
      return DexClass(className, superClass, interfaces, methodCount, fieldCount, isAbstract, isInterface, isEnum)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      className,
      superClass,
      interfaces,
      methodCount,
      fieldCount,
      isAbstract,
      isInterface,
      isEnum,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DexClass) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApkAnalysisNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ApkAnalysisNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkAsset.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkComponent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkManifest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DexClass.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ApkAsset -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ApkComponent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ApkManifest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DexClass -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ApkAnalysisNative {
  fun openApkSession(packageName: String, callback: (Result<String>) -> Unit)
  fun closeApkSession(sessionId: String, callback: (Result<Unit>) -> Unit)
  fun getApkAssets(sessionId: String, callback: (Result<List<ApkAsset>>) -> Unit)
  fun getApkAssetsAt(sessionId: String, path: String, callback: (Result<List<ApkAsset>>) -> Unit)
  fun parseManifest(sessionId: String, callback: (Result<ApkManifest>) -> Unit)
  fun getDexPackages(sessionId: String, dexPaths: List<String>, packagePrefix: String, callback: (Result<List<String>>) -> Unit)
  fun getDexClasses(sessionId: String, dexPaths: List<String>, packageName: String, callback: (Result<List<DexClass>>) -> Unit)
  fun getClassSmali(sessionId: String, dexPaths: List<String>, className: String, callback: (Result<String>) -> Unit)
  fun decompileClass(sessionId: String, dexPaths: List<String>, className: String, callback: (Result<String>) -> Unit)
  fun searchDexClasses(sessionId: String, dexPaths: List<String>, keyword: String, callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by ApkAnalysisNative. */
    val codec: MessageCodec<Any?> by lazy {
      ApkAnalysisNativePigeonCodec()
    }
    /** Sets up an instance of `ApkAnalysisNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ApkAnalysisNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.openApkSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.openApkSession(packageNameArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.closeApkSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.closeApkSession(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.getApkAssets$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.getApkAssets(sessionIdArg) { result: Result<List<ApkAsset>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.getApkAssetsAt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val pathArg = args[1] as String
            api.getApkAssetsAt(sessionIdArg, pathArg) { result: Result<List<ApkAsset>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.parseManifest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.parseManifest(sessionIdArg) { result: Result<ApkManifest> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.getDexPackages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val dexPathsArg = args[1] as List<String>
            val packagePrefixArg = args[2] as String
            api.getDexPackages(sessionIdArg, dexPathsArg, packagePrefixArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.getDexClasses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val dexPathsArg = args[1] as List<String>
            val packageNameArg = args[2] as String
            api.getDexClasses(sessionIdArg, dexPathsArg, packageNameArg) { result: Result<List<DexClass>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.getClassSmali$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val dexPathsArg = args[1] as List<String>
            val classNameArg = args[2] as String
            api.getClassSmali(sessionIdArg, dexPathsArg, classNameArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.decompileClass$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val dexPathsArg = args[1] as List<String>
            val classNameArg = args[2] as String
            api.decompileClass(sessionIdArg, dexPathsArg, classNameArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ApkAnalysisNative.searchDexClasses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val dexPathsArg = args[1] as List<String>
            val keywordArg = args[2] as String
            api.searchDexClasses(sessionIdArg, dexPathsArg, keywordArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ApkAnalysisNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ApkAnalysisNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
